version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: $MONGODB_DBNAME
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/db
  server:
    build: ./server
    depends_on:
      - mongo
    environment:
      - NODE_ENV=$API_NODE_ENV
      - PORT=$API_PORT
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_DBNAME=$MONGODB_DBNAME
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
      - /app/node_modules

