title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://uoft-frosh-orientation.github.io/orientation-website

aux_links:
  Github Repo: https://github.com/UofT-Frosh-Orientation/orientation-website/

favicon_ico: "../client/src/assets/logo/main-frosh-logo.ico"
