name: beta_deployment

on:
  workflow_dispatch:

  push:
    branches:
      - dev

concurrency: beta-deployment

env:
  REGISTRY: ${{ secrets.DIGITALOCEAN_CONTAINER_URL }}
  TAG: beta
  SERVER_IMAGE_NAME: "orientation-server"
  CLIENT_IMAGE_NAME: "orientation-client"
  DIGITALOCEAN_API_KEY: ${{ secrets.DIGITALOCEAN_API_KEY }}

jobs:
  build_server:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build server image
        run: cd server && docker build -t $(echo $REGISTRY)/$(echo $SERVER_IMAGE_NAME):beta -f beta.Dockerfile .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Remove old server image
        run: if [ ! -z "$(doctl registry repository list | grep "$(echo $SERVER_IMAGE_NAME)")" ]; then doctl registry repository delete-tag $(echo $SERVER_IMAGE_NAME) $(echo $TAG) --force; else echo "No repository"; fi


      - name: Push server image to container registry
        run: docker push $(echo $REGISTRY)/$(echo $SERVER_IMAGE_NAME):beta

  build_client:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build client image
        run: cd client && docker build -t $(echo $REGISTRY)/$(echo $CLIENT_IMAGE_NAME):beta -f beta.Dockerfile .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Remove old client image
        run: if [ ! -z "$(doctl registry repository list | grep "$(echo $CLIENT_IMAGE_NAME)")" ]; then doctl registry repository delete-tag $(echo $CLIENT_IMAGE_NAME) $(echo $TAG) --force; else echo "No repository"; fi

      - name: Push client image to container registry
        run: docker push $(echo $REGISTRY)/$(echo $CLIENT_IMAGE_NAME):beta
